# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c58b135ce0904c5f69abd00019d24d85babb9f4311d978952bb692ed21433be7ddce2f09fb430548fbf5048af3a393659ee60e0f08096d8f08488f03982e22e

test:
  secret_key_base: e81f4474608c750f48f5d2f5d007b6c577888a58c235d695860b6db02549793c717df04b0f593ece42089e288bd478322848f22e9816a59f946ec815501e1506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
